from torch_geometric.data import Data
from etnn.combinatorial_data import Cell

NUM_FEATURES = 13 # Match the number of features generated by process_ligand_sdf/process_protein_pdb

def atom_lift(graph: Data) -> set[Cell]:
    cells = set()
    X = graph.x
    for i in range(X.size(0)):
        # Map to ensure all features are floats
        cells.add((frozenset([i]), tuple(map(float, X[i].tolist()))))
    return cells

atom_lift.num_features = NUM_FEATURES
